spring:
  profiles:
    active: cloud
---
spring:
  profiles: cloud
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/dev
    username: root
    password: dbpass
    initialize: true
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-kb.cfapps.io/eureka/
  instance:
    hostname: users-kb.cfapps.io
    nonSecurePort: 80
ribbon:
  eureka:
    enabled: true
---
application:
  name: threedeemodel
spring:
  profiles: lattice
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/dev
    username: root
    password: dbpass
    initialize: true
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 9011
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    hostname: ${vcap.application.uris[0]:localhost:9006}
    nonSecurePort: 80
ribbon:
  eureka:
    enabled: true
---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/dev
    username: root
    password: dbpass
    initialize: true
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 9011
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true
